---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/6 16:20
---
DemoCfg = {}
DemoCfg.mainAvatarID = -1 ---主角色ID
DemoCfg.mapID = 1 ---地图ID

return DemoCfg