---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/6 16:20
---
DemoCfg = {}
DemoCfg.mainAvatarID = -1 ---主角色ID
DemoCfg.mapID = 1 ---地图ID
DemoCfg.starUpRateMap =  ---星级提升 属性上升倍率
{
    [1] = 1,
    [2] = 1.5,
    [3] = 1.8,
    [4] = 2.2,
    [5] = 2.5
}
return DemoCfg