---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/3 15:13
--- UI界面配置

---@class UIPanelCfg
---@field classPath string 页面类的路径
---@field prefabPath string prefab路径

UIPanelCfg = {}
UIPanelCfg.mainMenu = {classPath = "Modules.UI.MainMenuPanel", prefabPath = "Prefabs/UI/MainMenu/MainMenu.prefab"}
UIPanelCfg.growUp = {classPath = "Modules.UI.GrowUp.GrowUpPanel", prefabPath = "Prefabs/UI/GrowUp/GrowUpPanel.prefab"}