---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/7 13:26
--- 角色数据
local SData = require("Modules.WarScene.Model.SData")
local WarData = require("Modules.WarScene.Model.WarData")
local AvatarData = {}

AvatarData.HeroInfo =
{
    {
        id = -1,
        starLv = 1,
        equips =
        {
            {index = 1, equipId = 0},
            {index = 2, equipId = 0},
            {index = 3, equipId = 0},
            {index = 4, equipId = 0},
            {index = 5, equipId = 0},
            {index = 6, equipId = 0},
        }
    }
}

--获取角色数据
function AvatarData.GetHeroData(id)
    for i = 1, #AvatarData.HeroInfo do
        if AvatarData.HeroInfo[i].id == id then
            return AvatarData.HeroInfo[i]
        end
    end
end

function AvatarData.GetHeroSData(id)
    return SData.GetAvatarSData(id)
end
--获取角色属性
function AvatarData.GetHeroAttr(id)
    local data = AvatarData.GetHeroData(id)
    local orgData = SData.GetAvatarSData(id)
    local rate = DemoCfg.starUpRateMap[data.starLv]
    return {atk = orgData.atk * rate, def = orgData.def * rate, maxHp = orgData.maxHp * rate}
end

function AvatarData.UpStarLv(id)
    local data = AvatarData.GetHeroData(id)
    data.starLv = data.starLv + 1
    local afterAttr = AvatarData.GetHeroAttr(id)
    local avatar = WarData.GetAvatarById(id)
    avatar.data.maxHp = afterAttr.maxHp
    avatar.data.atk = afterAttr.atk
    avatar.data.def = afterAttr.def
    for i = 1, #data.equips do
        data.equips[i].equipId = 0
    end
end

function AvatarData.AutoEquip(id)
    local data = AvatarData.GetHeroData(id)
    for i = 1, #data.equips do
        data.equips[i].equipId = data.equips[i].index ---临时处理 自动装备
    end
end

return AvatarData
