---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/1/31 13:33
--- 敌我数据

local SData = {}

SData.myArmyList = {
    {prefab="Prefabs/Avatars/Kanna.prefab", data={id=-1, hp=5000, maxHp=3000, side=1}},
    {prefab="Prefabs/Avatars/Role.prefab", data={id=-2, hp=5000, maxHp=5000, side=1}},
    {prefab="Prefabs/Avatars/Kanna2.prefab", data={id=-3, hp=5000, maxHp=5000, side=1}},
}


SData.enemyList = {
    {prefab="Prefabs/Avatars/monster_xiong.prefab", data={id=-1, hp=600, maxHp=600, side=2}},
    {prefab="Prefabs/Avatars/monster_02.prefab", data={id=-1, hp=300, maxHp=300, side=2}},
    {prefab="Prefabs/Avatars/monster_02.prefab", data={id=-1, hp=300, maxHp=300, side=2}},
}

return SData