---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/1/31 13:33
--- 表格数据

local insert = table.insert
local sort = table.sort

local SData = {}
SData.avatar = require("Data.Excel.avatar") --角色表数据
SData.monster = require("Data.Excel.monster") --怪物表数据
SData.monsterPoint = require("Data.Excel.monsterPoint") --刷怪点表数据
SData.equip = require("Data.Excel.equip") --装备表数据
SData.pools = require("Data.Excel.pools") --奖池表

---获取地图数据
SData.mapSData = {} --地图数据缓存
function SData.GetMonsterPointSData(mapID)
    if SData.mapSData[mapID] == nil then
        local list = {}
        for i = 1, #SData.monsterPoint.Data do
            local info = SData.monsterPoint.Data[i]
            if info.mapID == mapID then
                insert(list, info)
            end
        end
        if next(list) ~= nil then
            sort(list, function(a, b) return a.id < b.id end)
            SData.mapSData[mapID] = list
        end
    end
    return SData.mapSData[mapID]
end

---获取已经开启的奖池ID
function SData.GetOpenPools()
    local list = {}
    for i = 1, #SData.pools.Data do
        local info = SData.pools.Data[i]
        if info.flag == 1 then
            insert(list, info.id)
        end
    end
    return list
end

return SData