---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/1/31 13:33
--- 表格数据

local insert = table.insert
local sort = table.sort

local SData = {}
SData.avatar = require("Data.Excel.avatar") --角色表数据
SData.monster = require("Data.Excel.monster") --怪物表数据
SData.monsterPoint = require("Data.Excel.monsterPoint") --刷怪点表数据
SData.equip = require("Data.Excel.equip") --装备表数据

function SData.GetAvatarSData(id)
    return SData.avatar[id]
end

function SData.GetMonsterSData(id)
    return SData.monster[id]
end

function SData.GetEquipSData(id)
    return SData.equip[id]
end

SData.mapSData = {} --地图数据缓存
function SData.GetMonsterPointSData(mapID)
    if SData.mapSData[mapID] == nil then
        local list = {}
        for i = 1, #SData.monsterPoint do
            local info = SData.monsterPoint[i]
            if info.mapID == mapID then
                insert(list, info)
            end
        end
        if next(list) ~= nil then
            sort(list, function(a, b) return a.id < b.id end)
            SData.mapSData[mapID] = list
        end
    end
    return SData.mapSData[mapID]
end

return SData