---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/3/6 10:23
--- 游戏控制台
---@class ConsoleView:LuaObj
local ConsoleView = class("ConsoleView", LuaObj)

function ConsoleView.ShowOrHide()
    if not ConsoleView.instance then
        ConsoleView.instance = ConsoleView.New()
        return
    end
    if ConsoleView.instance.gameObject.activeSelf == false then
        ConsoleView.instance:Show()
    else
        ConsoleView.instance:Hide()
    end
end

function ConsoleView:Ctor()
    --print("Login:Ctor")
    ConsoleView.super.Ctor(self, "Prefabs/Common/ConsoleView.prefab", nil, UIMgr.GetLayer(UILayerName.top))


    AddButtonHandler(self.transform:Find("ExitBtn").gameObject, PointerHandler.CLICK, handler(self, self.ExitHandler))
    AddButtonHandler(self.transform:Find("CloseBtn").gameObject, PointerHandler.CLICK, handler(self, self.CloseHandler))
end

function ConsoleView:ExitHandler()
    self:Hide()
    Game.Relaunch()
end

function ConsoleView:CloseHandler()
    self:Hide()
end
return ConsoleView