---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by VIVA.
--- DateTime: 2023/2/26 0:04
---

local AvatarBase = require("Modules.WarScene.View.AvatarBase.AvatarBase")
local WarAvatar = require("Modules.WarScene.View.WarAvatar")
local DamageManager = require("Modules.WarScene.Manager.DamageManager")
local WarData = require("Modules.WarScene.Model.WarData")
local SkillBase = require("Modules.WarScene.Controller.Skill.SkillBase")
---@class SkillJumpAttack:SkillBase
local SkillJumpAttack = class("SkillJumpAttack", SkillBase)

---@param avatar WarAvatar
function SkillJumpAttack:Begin(avatar, callBack)
    SkillJumpAttack.super.Begin(self, avatar, callBack)

    self.avatar.aniEvent:SetListenerByMsg(WarAvatar.ANI_EVENT_SKILL_HIT, function()
        self.avatar.target:GetHurt(600)
        local nativeScaleY = self.avatar.target.transform.localScale.y
        self.avatar.target.transform:DOScaleY(nativeScaleY * 0.4, 0.1)
        DelayedCall(1, function()
            self.avatar.target.transform:DOScaleY(nativeScaleY, 0.5)
        end)
    end)

    self.avatar:PlaySkillName()
    DelayedCall(0.5, function()
        self.avatar:PlayAnimation(AvatarBase.ANI_SKILL_NAME,nil, handler(self,self.Over))
    end)
end

function SkillJumpAttack:Over()
    SkillJumpAttack.super.Over(self)
    self.avatar:PlayAnimation(AvatarBase.ANI_IDLE_NAME)
    self.avatar.aniEvent:SetListenerByMsg(WarAvatar.ANI_EVENT_SKILL_HIT, nil)
end


return SkillJumpAttack