---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/2/8 14:46
--- 技能旋风斩

local AvatarBase = require("Modules.WarScene.View.AvatarBase.AvatarBase")
local DamageManager = require("Modules.WarScene.Manager.DamageManager")
local WarData = require("Modules.WarScene.Model.WarData")
local SkillBase = require("Modules.WarScene.Controller.Skill.SkillBase")
---@class SkillWhirlwind:SkillBase
local SkillWhirlwind = class("SkillWhirlwind", SkillBase)

local HURT_GAP_TIME = 0.2
local SKILL_TOTAL_TIME = 2
function SkillWhirlwind:Begin(avatar, callBack)
    SkillWhirlwind.super.Begin(self, avatar, callBack)

    self.avatar:PlayAnimation(AvatarBase.ANI_SKILL_NAME)

    local grids = WarData.GetAroundGrids(self.avatar.x, self.avatar.z, nil, true)
    local checkAndHurt
    checkAndHurt = function()
        local enemy ---@type WarAvatar
        for x, tb in pairs(grids) do
            for z, v in pairs(tb) do
                enemy = WarData.GetAvatarByLoc(x,z)
                if enemy and enemy.data.side ~= self.avatar.data.side and enemy.moving ~= true then
                    --print("你妹啊~")
                    enemy:GetHurt(DamageManager.GetHurtValue(self.avatar.data, enemy.data)/2)
                end
            end
        end
        self.loopFun = DelayedCall(HURT_GAP_TIME,checkAndHurt)
    end
    checkAndHurt()

    DelayedCall(SKILL_TOTAL_TIME, function()
        StopDelayedCall(self.loopFun)
        self.avatar:PlayAnimation(AvatarBase.ANI_IDLE_NAME)
        self:Over()
    end)
end

return SkillWhirlwind