---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/2/8 14:48
--- 技能基类

local WarAvatar = require("Modules.WarScene.View.WarAvatar")
---@class SkillBase
local SkillBase = class("SkillBase")

function SkillBase:Begin(avatar, callback)
    self.avatar = avatar ---@type WarAvatar
    self.callback = callback
    self.avatar.skillMarkTime = os.clock()
end

function SkillBase:Over()
    if self.callback then
        self.callback()
    end
end

return SkillBase