---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/2/23 18:15
---
local TeamModel = {}
TeamModel.eventDefine =
{
    autoAddTeam = "autoAddTeam", --进队
    removeTeam = "removeTeam", --离队
}
return TeamModel
