//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_Universal_CameraExtensionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("CameraExtensions");
		L.RegFunction("GetUniversalAdditionalCameraData", GetUniversalAdditionalCameraData);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUniversalAdditionalCameraData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Camera arg0 = (UnityEngine.Camera)ToLua.CheckObject(L, 1, typeof(UnityEngine.Camera));
			UnityEngine.Rendering.Universal.UniversalAdditionalCameraData o = UnityEngine.Rendering.Universal.CameraExtensions.GetUniversalAdditionalCameraData(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

