---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/3/1 15:13
---
---@class UI.DrawCard.Character_1_feature
---@field New fun():UI.DrawCard.OpenCardShow
local Character_1_feature = class("UI.DrawCard.Character_1_feature")
local fxUrl = "Effect/Prefabs/fx_starShine.prefab"
local step1_scale = Vector2.New(1.5,1.5)
local step1_start_pos = Vector2.New(300,340)
local step1_end_pos = Vector2.New(300,510)
local step1_fx_pos = Vector2.New(0,-50)
local step2_scale = Vector2.New(1.8,1.8)
local step2_start_pos = Vector2.New(180,260)
local step2_end_pos = Vector2.New(0,260)
local step2_fx_pos = Vector2.New(0,200)
function Character_1_feature:Ctor(go, endCb)
    self.gameObject = go ---@type UnityEngine.GameObject
    self.transform = self.gameObject.transform
    self.mask = self.transform:Find("Mask").gameObject
    self.maskCg = GetComponent.CanvasGroup(self.mask)
    self.cg = GetComponent.CanvasGroup(self.gameObject)
    local fx = CreatePrefab(fxUrl, self.transform.parent)
    fx:SetActive(false)
    self.cg.alpha = 1
    self.maskCg.alpha = 1
    self.transform.localPosition = step1_start_pos
    self.transform.localScale = step1_scale
    self.gameObject:SetActive(true)

    local seq = DOTween.Sequence()
    ---第一阶段特写
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.5))
    seq:Join(self.transform:DOLocalMove(step1_end_pos, 2))
    seq:InsertCallback(1.2, function()
        fx.transform.localPosition = step1_fx_pos
        fx:SetActive(true)
    end)
    seq:AppendInterval(1.5)
    ---第二阶段特写
    seq:Append(self.maskCg:DOFade(1, 0.2))
    seq:AppendCallback(function()
        self.transform.localPosition = step2_start_pos
        self.transform.localScale = step2_scale
    end)
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.5))
    seq:Join(self.transform:DOLocalMove(step2_end_pos, 2))
    seq:AppendInterval(1.5)
    seq:InsertCallback(3.9 + 1, function()
        fx.transform.localPosition = step2_fx_pos
        fx:SetActive(false)
        fx:SetActive(true)
    end)
    ---结束
    seq:Append(self.maskCg:DOFade(1, 0.5))
    seq:Append(self.cg:DOFade(0, 0.25))
    seq:AppendCallback(function()
        RecyclePrefab(fx, fxUrl)
        endCb()
    end)
end

return Character_1_feature