---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/2/6 16:58
--- 伤害管理
local DamageMgr = {}

---计算伤害
function DamageMgr.GetHurtValue(data, targetData)
    local value = 0
    local atk = data.atk
    local def = targetData.def
    value = atk - def
    if value < 0 then
        value = 0
    end
    return value
end

return DamageMgr