---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/8 13:47
--- 道具通用Item
---@class UI.Common.CommonItem:LuaObj
---@field New fun(parent:UnityEngine.Transform, data:table):LuaObj
local CommonItem = class("UI.Common.CommonItem", LuaObj)
function CommonItem:Ctor(parent, data)
    CommonItem.super.Ctor(self, "Prefabs/Panel/Common/CommonItem.prefab", nil, parent)
    self.data = data
    self.bg = GetComponent.Image(self.transform:Find("bg").gameObject)
    self.icon = GetComponent.Image(self.transform:Find("icon").gameObject)
    self.light = self.transform:Find("light").gameObject

    self.vId = self.data.vId
    self.sData = self.data.sData
    self.quality = self.sData.quality

    self.bg.sprite = resMgr:LoadSpriteAtPath(DemoCfg.qualityBgMap[self.quality])
    self.icon.sprite = resMgr:LoadSpriteAtPath(string.format("%s%s.png", DemoCfg.equipIconPath, self.sData.icon))
    self:RefreshLight()
end

function CommonItem:RefreshLight()
    if self.quality < DemoCfg.equipQuality.purple then
        self.light:SetActive(false)
    else
        self.light:SetActive(true)
    end
end

return CommonItem