---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/2 17:51
--- UI管理器
local UIMgr = {}

---UI层级
UIMgr.UILayer = {} ---@type table<string, UnityEngine.Transform>

---层级名称定义 显示顺序由低到高s
local layer_scene = "Scene"
local layer_UI = "UI"
local layer_panel = "Panel"
local layer_UITop = "UITop"
local layer_alert = "Alert"
local layer_guide = "Guide"
local layer_top = "Top"

---panel容器
local panelContainer = {} ---@type table<string, UI.BasePanel>

---初始化UI层级
---@param UICanvas UnityEngine.Transform
function UIMgr.InitLayer(UICanvas)
    UIMgr.UILayer.scene = UICanvas.transform:Find(layer_scene)
    UIMgr.UILayer.UI = UICanvas.transform:Find(layer_UI)
    UIMgr.UILayer.panel = UICanvas.transform:Find(layer_panel)
    UIMgr.UILayer.UITop = UICanvas.transform:Find(layer_UITop)
    UIMgr.UILayer.alter = UICanvas.transform:Find(layer_alert)
    UIMgr.UILayer.guide = UICanvas.transform:Find(layer_guide)
    UIMgr.UILayer.top = UICanvas.transform:Find(layer_top)
end

---打开页面
---@param cfg UIPanelCfg 页面配置
function UIMgr.OpenPanel(cfg, ...)
    if cfg == nil then
        LogError("OpenPanel 页面配置为空")
        return
    end
    local classPath = cfg.classPath
    if classPath == nil then
        LogError("OpenPanel 没有配置classPath")
        return
    end
    if panelContainer[classPath] ~= nil then
        LogWarning(classPath.." 此页面已经打开")
        return
    end
    local class = require(classPath)
    if class == nil then
        return
    end
    panelContainer[classPath] = class.New(...)
end

---关闭界面
---@param cfg UIPanelCfg 页面配置
function UIMgr.ClosePanel(cfg)
    local panel = UIMgr.GetPanel(cfg)
    if panel then
        panel:Destroy()
        panelContainer[cfg.classPath] = nil
    else
        LogWarning(cfg.classPath.." 此页面未打开")
    end
end

---获取页面
---@param cfg UIPanelCfg 页面配置
function UIMgr.GetPanel(cfg)
    if cfg == nil then
        LogError("GetPanel 页面配置为空")
        return
    end
    local classPath = cfg.classPath
    if classPath == nil then
        LogError("GetPanel 没有配置classPath")
        return
    end
    local panel = panelContainer[classPath]
    if panel == nil then
        return
    end
    return panelContainer[classPath]
end

---检查页面引用是否清除
---@param cfg UIPanelCfg 页面配置
function UIMgr.CheckPanelClean(cfg)
    local panel = UIMgr.GetPanel(cfg)
    if panel then
        panelContainer[cfg.classPath] = nil
    end
end

return UIMgr