---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/2/20 16:03
---
---@class UI.DrawCard.CardControl:LuaObj
---@field New fun():UI.DrawCard.CardControl
local CardControl = class("UI.DrawCard.CardControl", LuaObj)
function CardControl:Ctor(parent, id)

end

function CardControl:Open()

end

return CardControl