---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/27 16:51
---
local OpenCardShow = class("UI.DrawCard.OpenCardShow")
function OpenCardShow:Ctor(go, data)

end

return OpenCardShow