---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/2/17 16:15
---
---@class UI.DrawCard.PoolView:LuaObj
---@field New fun():UI.DrawCard.PoolView
local PoolView = class("UI.DrawCard.PoolView", LuaObj)
function PoolView:Ctor(parent, poolId)
    PoolView.super.Ctor(self, "Prefabs/Panel/DrawCard/NormalPoolView.prefab", nil, parent)
    self.poolId = poolId
    self.BtnOnce = self.transform:Find("Bottom/BtnOnce").gameObject
    self.BtnTenth = self.transform:Find("Bottom/BtnTenth").gameObject
    AddButtonHandler(self.BtnOnce, PointerHandler.CLICK, self.OnBtnOnceClick, self)
    AddButtonHandler(self.BtnTenth, PointerHandler.CLICK, self.OnBtnTenthClick, self)
end

function PoolView:OnBtnOnceClick()

end

function PoolView:OnBtnTenthClick()

end

function PoolView:OnDestroy()
    RemoveButtonHandler(self.BtnOnce, PointerHandler.CLICK, self.OnBtnOnceClick, self)
    RemoveButtonHandler(self.BtnTenth, PointerHandler.CLICK, self.OnBtnTenthClick, self)
end

return PoolView