---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/17 16:15
--- 抽奖页面
local DrawCardModel = require("Modules.UI.DrawCard.Model.DrawCardModel")
---@class UI.DrawCard.PoolControl:LuaObj
---@field New fun():UI.DrawCard.PoolControl
local PoolControl = class("UI.DrawCard.PoolControl", LuaObj)
function PoolControl:Ctor(parent, poolId)
    self.poolId = poolId
    self.sData = SData.pools.GetData(self.poolId)
    local prefab = string.format("Prefabs/Panel/DrawCard/%s.prefab", self.sData.prefab)
    PoolControl.super.Ctor(self, prefab, nil, parent)

    self.BgImage = self.transform:Find("bg/BgImage")
    self.BtnOnce = self.transform:Find("Bottom/BtnOnce").gameObject
    self.BtnTenth = self.transform:Find("Bottom/BtnTenth").gameObject
    AddButtonHandler(self.BtnOnce, PointerHandler.CLICK, self.OnBtnOnceClick, self)
    AddButtonHandler(self.BtnTenth, PointerHandler.CLICK, self.OnBtnTenthClick, self)
end

function PoolControl:OnBtnOnceClick()
    EventMgr.DispatchEvent(DrawCardModel.eventDefine.oneDraw)
end

function PoolControl:OnBtnTenthClick()
    EventMgr.DispatchEvent(DrawCardModel.eventDefine.tenDraw)
end

function PoolControl:OnDestroy()
    RemoveButtonHandler(self.BtnOnce, PointerHandler.CLICK, self.OnBtnOnceClick, self)
    RemoveButtonHandler(self.BtnTenth, PointerHandler.CLICK, self.OnBtnTenthClick, self)
end

return PoolControl