---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/2/17 16:14
---
---@class UI.DrawCard.PoolSelectBtn:LuaObj
---@field New fun():UI.DrawCard.PoolSelectBtn
local PoolSelectBtn = class("UI.DrawCard.PoolSelectBtn", LuaObj)
function PoolSelectBtn:Ctor(parent, poolId)
    PoolSelectBtn.super.Ctor(self, "Prefabs/Panel/DrawCard/PoolSelectBtn.prefab", nil, parent)
    self.poolId = poolId
    self.btn = self.transform:Find("btn").gameObject
    self.text = GetComponent.Text(self.transform:Find("Text").gameObject)
    AddButtonHandler(self.btn, PointerHandler.CLICK, self.OnBtnClick, self)
end

function PoolSelectBtn:OnBtnClick()

end

function PoolSelectBtn:OnDestroy()
    RemoveButtonHandler(self.btn, PointerHandler.CLICK, self.OnBtnClick, self)
end

return PoolSelectBtn