---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/3/6 17:24
--- 滚动卡牌
local url = "Prefabs/Panel/DrawCard/RollCards.prefab"
---@class UI.DrawCard.RollCards
---@field New fun():UI.DrawCard.RollCards
local RollCards = class("UI.DrawCard.RollCards")
function RollCards:Ctor(parent, moveTime)
    self.gameObject = CreatePrefab(url, parent)
    self.transform = self.gameObject.transform
    self.moveTime = moveTime or 1
    self:ResetList()
    self:StartMove()
end

function RollCards:ResetList()
    self.itemList = {} ---@type table<number, UnityEngine.Transform>
    self.posList = {}
    for i = 1, self.transform.childCount do
        local tra = self.transform:GetChild(i - 1)
        local pos = tra.localPosition
        table.insert(self.itemList, tra)
        table.insert(self.posList, pos)
    end
end

function RollCards:StartMove(moveTime)
    if moveTime then
        self.moveTime = moveTime
    end
    local moveFunc = function()
        self.seq = DOTween.Sequence()
        for i = 1, #self.itemList do
            local item = self.itemList[i]
            if self.posList[i + 1] then
                local targetY = self.posList[i + 1].y
                if i == 1 then
                    self.seq:Append(item:DOLocalMoveY(targetY, self.moveTime):SetEase(DOTWEEN_EASE.Linear))
                else
                    self.seq:Join(item:DOLocalMoveY(targetY, self.moveTime):SetEase(DOTWEEN_EASE.Linear))
                end
            end
        end
        self.seq:AppendCallback(function()
            local last = table.remove(self.itemList, #self.itemList)
            last.transform.localPosition = self.posList[1]
            table.insert(self.itemList, 1, last)
        end)
    end
    Happy.RegisterLoopFun(self, moveFunc, self.moveTime)
end


return RollCards