---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/3/6 17:24
--- 滚动卡牌
local url = "Prefabs/Panel/DrawCard/RollCards.prefab"
---@class UI.DrawCard.RollCards
---@field New fun():UI.DrawCard.RollCards
local RollCards = class("UI.DrawCard.RollCards")
function RollCards:Ctor(parent, moveTime)
    self.gameObject = CreatePrefab(url, parent)
    self.transform = self.gameObject.transform
    self.moveTime = moveTime or 1
    self:ResetList()
    self:StartMove()
end

function RollCards:ResetList()
    self.itemList = {} ---@type table<number, UnityEngine.Transform>
    self.posList = {}
    for i = 1, self.transform.childCount do
        local tra = self.transform:GetChild(i - 1)
        local pos = tra.localPosition
        table.insert(self.itemList, {tra = tra, rollIndex = i})
        table.insert(self.posList, pos)
    end
end

function RollCards:StartMove(moveTime)
    if moveTime then
        self.moveTime = moveTime
    end
    local moveFunc = function()
        self.seq = DOTween.Sequence()
        for i = 1, #self.itemList do
            local item = self.itemList[i]
            local target = self.posList[item.rollIndex + 1]

            if target then
                if i == 1 then
                    self.seq:Append(item.tra:DOLocalMove(target, self.moveTime):SetEase(DOTWEEN_EASE.Linear))
                else
                    self.seq:Join(item.tra:DOLocalMove(target, self.moveTime):SetEase(DOTWEEN_EASE.Linear))
                end
                item.rollIndex = item.rollIndex + 1
            else
                --local last = table.remove(self.itemList)
                item.tra.localPosition = self.posList[1]
                item.rollIndex = 1
                --table.insert(self.itemList, 1, last)
            end
        end
    end
    Happy.RegisterLoopFun(self, moveFunc, self.moveTime+0.01)
end

function RollCards:Recycle()
    RecyclePrefab(self.gameObject, url)
    Happy.RegisterLoopFun(self)
end

return RollCards