---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/3/8 16:54
---
---@class UI.DrawCard.SearchShow
---@field New fun():UI.DrawCard.SearchShow
local SearchShow = class("UI.DrawCard.SearchShow")
function SearchShow:Ctor(go, callback)
    self.gameObject = go ---@type UnityEngine.GameObject
    self.transform = self.gameObject.transform ---@type UnityEngine.Transform

    self.imageList = {}
    for i = 1, 3 do
        local image = self.transform:Find("Image"..i)
        image.gameObject:SetActive(false)
        table.insert(self.imageList, image)
    end
    self.maskCg = GetComponent.CanvasGroup(self.transform:Find("mask").gameObject)
    self.maskCg.gameObject:SetActive(true)
    self.gameObject:SetActive(true)
    self:ShowImage(1)
    local seq = DOTween.Sequence()
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.25))

    seq:AppendInterval(0.8)
    seq:Append(self.maskCg:DOFade(1, 0.25))
    seq:AppendCallback(function()
        self:ShowImage(2)
    end)
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.25))

    seq:AppendInterval(0.8)
    seq:Append(self.maskCg:DOFade(1, 0.25))
    seq:AppendCallback(function()
        self:ShowImage(3)
    end)
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.25))

    seq:AppendInterval(0.8)
    seq:Append(self.maskCg:DOFade(1, 0.25))
    seq:AppendCallback(function()
        self:ShowImage(4)
    end)
    seq:AppendInterval(0.2)
    seq:Append(self.maskCg:DOFade(0, 0.25))

    seq:AppendInterval(0.8)
    seq:Append(self.maskCg:DOFade(1, 0.25))
    seq:AppendInterval(0.2)
    seq:AppendCallback(function()
        self:ShowImage(0)
    end)
    seq:Append(self.maskCg:DOFade(0, 0.25))
    seq:AppendCallback(function()
        self.gameObject:SetActive(false)
        if callback then
            callback()
        end
    end)
end

function SearchShow:ShowImage(index)
    for i = 1, #self.imageList do
        if i == index then
            self.imageList[i].gameObject:SetActive(true)
        else
            self.imageList[i].gameObject:SetActive(false)
        end
    end
end

return SearchShow