---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by VIVA.
--- DateTime: 2023/2/24 0:49
--- 到达BOSS的指引箭头

---@class BossArrow:LuaObj
local BossArrow = class("BossArrow",LuaObj)

function BossArrow:Ctor(bossAvatar)
    BossArrow.super.Ctor(self, "Prefabs/War/BossArrow.prefab", nil, UILayerName.top)
    self.cam = Camera.main
    self.uiCamera = GetComponent.Canvas(Game.UICanvas).worldCamera
    self.bossAvatar = bossAvatar
    self.rect = GetComponent.RectTransform(self.gameObject)
    self.iconRect = GetComponent.RectTransform(self.transform:Find("Bg/iconBg/icon").gameObject)
    self.cg = GetComponent.CanvasGroup(self.gameObject)

    self.tween = GetComponent.DOTweenAnimation(self.transform:Find("Bg").gameObject)

    self.maxX = (Screen.width/2)*0.82
    self.minX = -self.maxX
    self.maxY = (Screen.height/2)*0.73
    self.minY = -self.maxY
    self.baseDirection = Vector2.New(0, self.maxY)

end

---飞向图标的衔接效果
function BossArrow:FlyToIcon(fromGo, callBack)
    self.cg.alpha = 0
    self.tween:DOPause()
    local fromRt = GetComponent.RectTransform(fromGo)
    self:Update()
    local seq = DOTween.Sequence()
    seq:Append(fromRt:DOSizeDelta(self.iconRect.sizeDelta, 0.5))
    seq:Join(fromRt:DOMove(self.iconRect.position, 0.5))
    seq:Append(self.cg:DOFade(1, 0.3))
    seq:AppendCallback(function()
        DelayedCall(0.5, function()
            self.tween:DOPlay()
        end)

        --print("你妹啊~1", self.iconRect.position.x, self.iconRect.position.y, self.iconRect.position.z)
        --print("你妹啊~2", fromRt.position.x, fromRt.position.y, fromRt.position.z)
        if callBack then
            callBack()
        end
    end)
end

function BossArrow:Update()
    local screenP = self.cam:WorldToScreenPoint(self.bossAvatar.transform.position)
    local hehe, p = RectTransformUtility.ScreenPointToLocalPointInRectangle(self.transform.parent, screenP, self.uiCamera, Vector2.zero)
    if screenP.z < 0 then
        p.x = -p.x
        p.y = -p.y
    end
    local changed = self:FixLimit(p)
    if changed == false then
        if not self.hideDelay then
            self.hideDelay = DelayedCall(3, function()
                self.cg:DOFade(0, 0.5):OnComplete(function()
                    self.cg.alpha = 1
                    self:Recycle()
                end)
            end)
        end
        self.rect.localEulerAngles = Vector3.New(0,0, 180)
        self.rect.anchoredPosition = p + Vector2.New(0, 300)
    else
        self.rect.anchoredPosition = p
        self.rect.localEulerAngles = Vector3.New(0,0, Vector2.Angle(self.baseDirection, self.rect.anchoredPosition))
    end
    self.iconRect.localEulerAngles = Vector3.New(0,0, -self.rect.localEulerAngles.z)
end

function BossArrow:FixLimit(p)
    local oldX = p.x
    local oldY = p.y
    p.x = math.max(p.x, self.minX)
    p.x = math.min(p.x, self.maxX)
    p.y = math.max(p.y, self.minY)
    p.y = math.min(p.y, self.maxY)

    return (oldX ~= p.x or oldY ~= p.y)
end

return BossArrow