---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by VIVA.
--- DateTime: 2023/2/24 0:49
--- 到达BOSS的指引箭头

---@class BossArrow:LuaObj
local BossArrow = class("BossArrow",LuaObj)

function BossArrow:Ctor(bossAvatar)
    BossArrow.super.Ctor(self, "Prefabs/War/BossArrow.prefab", nil, UILayerName.top)
    self.cam = Camera.main
    self.uiCamera = GetComponent.Canvas(Game.UICanvas).worldCamera
    self.bossAvatar = bossAvatar
    self.rect = GetComponent.RectTransform(self.gameObject)

    self.maxX = (Screen.width/2)*0.9
    self.minX = -self.maxX
    self.maxY = (Screen.height/2)*0.9
    self.minY = -self.maxY
end

function BossArrow:Update()
    local screenP = self.cam:WorldToScreenPoint(self.bossAvatar.transform.position)
    local hehe, p = RectTransformUtility.ScreenPointToLocalPointInRectangle(self.transform.parent, screenP, self.uiCamera, Vector2.zero)
end

return BossArrow