---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/2/8 16:31
--- 角色头顶UI容器

---@class HeadUI:LuaObj
local HeadUI = class("HeadUI",LuaObj)


function HeadUI:Ctor(avatar)
    HeadUI.super.Ctor(self, "Prefabs/War/HeadUI.prefab", nil, UIMgr.GetLayer(UILayerName.scene))
    self.avatar = avatar ---@type WarAvatar
    self.worldTrans = avatar.transform
    self.offsetV2 = Vector2.New(0, 80)
    self.rect = GetComponent.RectTransform(self.gameObject)
    if avatar.transform:Find("uiPos") then
        self.worldTrans = avatar.transform:Find("uiPos")
        self.offsetV2 = Vector2.zero
    end
end

function HeadUI:SkillNameShow(name)
    name = name or "xuanfeng"
    local prefabPath = "Prefabs/War/SkillName.prefab"
    local gObj = CreatePrefab(prefabPath, self.transform)
    GetComponent.Image(gObj).sprite = resMgr:LoadSpriteAtPath("Textures/war/SkillName/"..name..".png")
    gObj.transform.localPosition = Vector3.New(0, 30,0)
    self.transform:SetAsLastSibling()
    gObj:SetActive(false)
    gObj:SetActive(true)
    DelayedCall(2, function()
        if isnull(gObj) ~= true then
            RecyclePrefab(gObj, prefabPath)
        end
    end)
end

function HeadUI:Update()

    if self.destroyed == true or self.gameObject.activeSelf == false then
        return
    end

    local cam = Camera.main
    local screenP = cam:WorldToScreenPoint(self.worldTrans.position)
    local uiCamera = GetComponent.Canvas(Game.UICanvas).worldCamera
    local hehe, p = RectTransformUtility.ScreenPointToLocalPointInRectangle(self.rect.parent, screenP, uiCamera, Vector2.zero)

    self.rect.anchoredPosition = p + self.offsetV2
end

function HeadUI:Show()
    HeadUI.super.Show(self)
    self:Update()
end

return HeadUI