---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2021/12/7 11:44
--- 血条

local LuaObj = require("Prayer.Core.LuaObj")
---@class HpBar:LuaObj
---@field New fun(bindObj:UnityEngine.GameObject, offsetV2:Vector2, data):HpBar
local HpBar = class("HpBar", LuaObj)

---@param bindObj UnityEngine.GameObject
function HpBar:Ctor(bindObj, offsetV2, data)
    HpBar.super.Ctor(self, "Prefabs/War/HpBar.prefab", nil, UIMgr.UILayer.scene)
    self.transform:SetAsFirstSibling()
    self.bindObj = bindObj
    self.offsetV2 = offsetV2 or Vector2.zero
    self.rect = GetComponent.RectTransform(self.gameObject)

    self.img = GetComponent.Image(self.transform:Find("progress").gameObject)
    GetComponent.Text(self.transform:Find("idText").gameObject).text = data.id
    self:ChangeHp(data.hp, data.maxHp)
end

function HpBar:ChangeHp(hp, maxHp, tween)
    if self.gameObject.activeSelf == false then
        self:Show()
    end
    local goal = hp/maxHp
    --print("HpBar:ChangeHp", hp, maxHp)
    if tween == true then
        local changeValue = math.abs(self.img.fillAmount - goal)
        self.img:DOFillAmount(goal, changeValue * 0.7)
    else
        self.img.fillAmount = goal
    end

    if self.autoHide then
        StopDelayedCall(self.autoHide)
    end
    self.autoHide = DelayedCall(3, function()
        self:Hide()
    end)
end

function HpBar:Update()
    if self.destroyed == true then
        return
    end
    local cam = Camera.main
    local screenP = cam:WorldToScreenPoint(self.bindObj.transform.position)

    local hehe, p = RectTransformUtility.ScreenPointToLocalPointInRectangle(self.rect.parent, screenP, nil, Vector2.zero)

    self.rect.anchoredPosition = p + self.offsetV2
    --print("HpBar:Update", p.x, p.y)
end

function HpBar:Show()
    HpBar.super.Show(self)
    self:Update()
end

return HpBar