---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by VIVA.
--- DateTime: 2023/1/25 19:27
--- 相机焦点对象
local WarAvatar = require("Modules.WarScene.View.WarAvatar")
local BehaviorConstants = require("Modules.WarScene.Model.BehaviorConstants")
---@class FocusAvatar:WarAvatar
---@field New fun(prefabPath:string, data, parent:UnityEngine.Transform):FocusAvatar
local FocusAvatar = class("FocusAvatar", WarAvatar)

function FocusAvatar:Ctor(prefabPath, data, parent)
    print("FocusAvatar:Ctor",  FocusAvatar.super.Ctor)
    FocusAvatar.super.Ctor(self, prefabPath, data, false, parent)

    self:RegisterAction(BehaviorConstants.NEW_WAVE_ENEMYS)
    self:RegisterAction(BehaviorConstants.CHECK_SAFE)
end

return FocusAvatar