---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/23 15:03
---
local AvatarData = require("Modules.WarScene.Model.AvatarData")
local WarData = require("Modules.WarScene.Model.WarData")
---@class UI.Team.TeamHeroItem:LuaObj
---@field New fun():UI.Team.TeamHeroItem
local TeamHeroItem = class("UI.Team.TeamHeroItem", LuaObj)
function TeamHeroItem:Ctor(parent, info)
    TeamHeroItem.super.Ctor(self, "Prefabs/Panel/Team/TeamHeroItem.prefab", nil, parent)
    self.info = info
    self.icon = GetComponent.Image(self.transform:Find("icon").gameObject)
    self.nameBg = GetComponent.Image(self.transform:Find("nameBg").gameObject)
    self.nameText = GetComponent.Text(self.transform:Find("nameBg/name").gameObject)
    self.inTeam = self.transform:Find("inTeam").gameObject

    self.icon.gameObject:SetActive(false)
    self.id = self.info.id
    local data = AvatarData.GetHeroSData(self.id)
    self.data = data
    self.nameText.text = data.name
    self.nameBg.color = DemoCfg.cardColorCfg[data.quality]
    self:RefreshInTeam()
end

function TeamHeroItem:RefreshInTeam()
    self.inTeam:SetActive(AvatarData.CheckInTeam(self.id))
end


return TeamHeroItem