---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/6 17:57
--- 成长界面装备格

---@class UI.GrowUp.GrowUpEquipItem:LuaObj
---@field New fun():LuaObj
local GrowUpEquipItem = class("UI.GrowUp.GrowUpEquipItem", LuaObj)
function GrowUpEquipItem:Ctor(gameObject, data)
    GrowUpEquipItem.super.Ctor(self, nil, gameObject)
    self.data = data
    self.attrPic = self.transform:Find("AttrPic").gameObject
    self.attrTextObj = self.transform:Find("Now").gameObject
    self.attrText = GetComponent.Text(self.attrTextObj)
end


return GrowUpEquipItem