---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/6 17:57
--- 成长界面装备格

---@class UI.GrowUp.GrowUpEquipItem:LuaObj
---@field New fun():LuaObj
local GrowUpEquipItem = class("UI.GrowUp.GrowUpEquipItem", LuaObj)
function GrowUpEquipItem:Ctor(gameObject, data)
    GrowUpEquipItem.super.Ctor(self, nil, gameObject)
    self.data = data
    self.equipId = data.equipId
    self.icon = self.transform:Find("Equip").gameObject
    self.iconImg = GetComponent.Image(self.icon)
    self:Refresh()
end

function GrowUpEquipItem:Refresh()
    if self.data.equipId == 0 then
        self.icon:SetActive(false)
    else
        self.icon:SetActive(true)
    end
end

function GrowUpEquipItem:SetEquip(data)
    if self.equipId ~= data.equipId then
        self:Refresh()
        self.equipId = data.equipId
        local sequence = DOTween.Sequence()
        sequence:AppendCallback(function()
            local fx = CreatePrefab("Effect/Prefabs/fx_light_show_short.prefab", self.transform)
            fx:Destroy(1)
        end)
        sequence:Append(self.icon.transform:DOScale(1.5, 0.25):SetEase(Happy.DOTWEEN_EASE.OutCubic))
        sequence:Append(self.icon.transform:DOScale(1, 0.15):SetEase(Happy.DOTWEEN_EASE.Linear))

    end
end

return GrowUpEquipItem