---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/3 17:23
--- 角色养成界面

---@class UI.GrowUp.GrowUpPanel:UI.BasePanel
---@field New fun():UI.GrowUp.GrowUpPanel
local GrowUpPanel = class("UI.GrowUp.GrowUpPanel", BasePanel)

function GrowUpPanel:OnInit()
    GrowUpPanel.super.OnInit(self)

end

function GrowUpPanel:RemoveListeners()
end

return GrowUpPanel