---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2021/12/2 15:31
--- 攻击

local BaseAction = require("Prayer.Core.BaseAction")
---@class AttackAction:BaseAction
local AttackAction = class("AttackAction", BaseAction)

function AttackAction:Ctor(avatar, bToLua, cAction, paramFloat, paramBool)
    AttackAction.super.Ctor(self, bToLua, cAction, paramFloat, paramBool)
    self.avatar = avatar ---@type WarAvatar

end

function AttackAction:OnStart()
    self.cAction:SetUpdateStatus(TaskStatus.Running)
    self.avatar:MoveEnd(true)
    self:Attack()
end

function AttackAction:Attack()
    if self.avatar:CheckDead() == true then
        --print("我死了不打了", self.avatar.data.id)
        return
    end
    if not self.avatar.target or self.avatar.target:CheckDead() == true then
        self.avatar.target = nil
        self.cAction:SetUpdateStatus(TaskStatus.Success)
        --local list = self.bToLua:GetActiveTasks()
        --print("AttackAction:AttackToDeath 已击杀目标~~", list.Length)
        return
    end
    if self.paused == true then
        print("暂停了", self.avatar.id)
        return
    end
    if self.avatar.target.moving == true then ---目标移动中先不打，等一会儿再来看看
        self.avatar:LookAtTarget()
        self.waitCall = DelayedCall(0.5, handler(self, self.AttackToDeath))
        return
    end

    self.avatar:Attack(function()
        self.cAction:SetUpdateStatus(TaskStatus.Success)
    end)
end

function AttackAction:OnPause(paused)
    --print("AttackAction:OnPause", paused)
    self.paused = paused

end

function AttackAction:OnBehaviorComplete()
    if self.cAction:GetUpdateStatus() == TaskStatus.Running then
        self.avatar:CancelAttack()
    end
end

function AttackAction:OnBehaviorRestart()
    --print("AttackAction:OnBehaviorRestart")
end

function AttackAction:OnEnd()
    --print("AttackAction:OnEnd")
end

return AttackAction