---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2023/1/31 16:12
--- 跟随队长

local BaseAction = require("Prayer.Core.BaseAction")
---@class FollowAction:BaseAction
local FollowAction = class("FollowAction", BaseAction)

function FollowAction:Ctor(avatar, bToLua, cAction, paramFloat, paramBool)
    FollowAction.super.Ctor(self, bToLua, cAction, paramFloat, paramBool)
    self.avatar = avatar ---@type WarAvatar

end

function FollowAction:OnStart()
    --print("你妹啊~")
    self.avatar:BeginFollow()
    self.cAction:SetUpdateStatus(TaskStatus.Success)
end

return FollowAction