---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2021/12/2 15:46
--- 找到敌方附近位置，并移动过去
---
local BaseAction = require("Prayer.Core.BaseAction")
local WarData = require("Modules.WarScene.Model.WarData")
---@class MoveToEnemyAction:BaseAction
local MoveToEnemyAction = class("MoveToEnemyAction", BaseAction)

function MoveToEnemyAction:Ctor(avatar, bToLua, cAction, paramFloat, paramBool)
    MoveToEnemyAction.super.Ctor(self, bToLua, cAction, paramFloat, paramBool)
    self.avatar = avatar ---@type WarAvatar
end

function MoveToEnemyAction:OnStart()
    if not self.avatar.target then
        return
    end
    self.avatar:EndFollow()
    self.avatar:StopMoving()
    ---Check攻击范围
    local grids = WarData.GetAroundGrids(self.avatar.x, self.avatar.z, self.avatar.attackRadius)
    --print("MoveToEnemyAction:OnStart", self.avatar.target.x, self.avatar.target.z, grids[self.avatar.target.x])
    if  grids[self.avatar.target.x] and grids[self.avatar.target.x][self.avatar.target.z] then
        --print("敌人能打到，不用走")
        self.cAction:SetUpdateStatus(TaskStatus.Success)
        return
    end

    self.cAction:SetUpdateStatus(TaskStatus.Running)

    local x,z,nearestPos = WarData.GetAroundNearestGrid(self.avatar.transform.position, self.avatar.target.x, self.avatar.target.z,
            nil, true, WarData.AvatarGrids)
    local nearestLoc = {x, z}

    self.avatar:MoveAStar(nearestPos, function()
        ---TEST
        --local nowGrid = WarData.gridGraph:GetNearest(self.avatar.transform.position, Pathfinding.NNConstraint.None).node ---@type Pathfinding.GridNode
        --if nowGrid.XCoordinateInGrid ~= self.avatar.x or nowGrid.ZCoordinateInGrid ~= self.avatar.z then
        --    print("移动出错啦~", self.avatar.data.id, nowGrid.XCoordinateInGrid, nowGrid.ZCoordinateInGrid, self.avatar.x, self.avatar.z)
        --end
        --
        --self.avatar.transform.position = SeekerToLua.IntToVector(WarData.gridGraph:GetNode(self.avatar.x, self.avatar.z).position)
        --if self.avatar.data.id < -1 then
        --    print("你妹啊", self.avatar.data.id, self.avatar.transform.position.x,
        --            self.avatar.transform.position.z, self.avatar.x, self.avatar.z)
        --end
        ---TEST
        self.cAction:SetUpdateStatus(TaskStatus.Success)
    end, nearestLoc)
    --DelayedCall(1, function()
    --    self.avatar:StopMoving()
    --end)

end

function MoveToEnemyAction:OnPause(paused)
    print("MoveToEnemyAction:OnPause", paused)
    self.paused = paused
end

return MoveToEnemyAction