---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2021/12/2 15:31
--- 尝试施放技能

local BaseAction = require("Prayer.Core.BaseAction")
---@class TryToCastSkillAction:BaseAction
local TryToCastSkillAction = class("TryToCastSkillAction", BaseAction)

function TryToCastSkillAction:Ctor(avatar, bToLua, cAction, paramFloat, paramBool)
    TryToCastSkillAction.super.Ctor(self, bToLua, cAction, paramFloat, paramBool)
    self.avatar = avatar ---@type WarAvatar
    self.skillCD = paramFloat ---技能CD
end

function TryToCastSkillAction:OnStart()
    self.cAction:SetUpdateStatus(TaskStatus.Running)
    self:AttackToDeath()
end

function TryToCastSkillAction:AttackToDeath()
    if self.avatar:CheckDead() == true then
        --print("我死了不打了", self.avatar.data.id)
        return
    end
    if not self.avatar.target or self.avatar.target:CheckDead() == true then
        self.avatar.target = nil
        self.cAction:SetUpdateStatus(TaskStatus.Success)
        --local list = self.bToLua:GetActiveTasks()
        --print("TryToCastSkillAction:AttackToDeath 已击杀目标~~", list.Length)
        return
    end
    if self.paused == true then
        print("暂停了", self.avatar.id)
        return
    end
    if self.avatar.target.moving == true then ---目标移动中先不打，等一会儿再来看看
    self.avatar:LookAtTarget()
        self.waitCall = DelayedCall(0.5, handler(self, self.AttackToDeath))
        return
    end

    self.avatar:Attack(handler(self, self.AttackToDeath))
end

function TryToCastSkillAction:OnPause(paused)
    --print("TryToCastSkillAction:OnPause", paused)
    self.paused = paused
    if paused == false then
        self:AttackToDeath()
    end
end

function TryToCastSkillAction:OnBehaviorComplete()
    --print("TryToCastSkillAction:OnBehaviorComplete")
end

function TryToCastSkillAction:OnBehaviorRestart()
    --print("TryToCastSkillAction:OnBehaviorRestart")
end

function TryToCastSkillAction:OnEnd()
    --print("TryToCastSkillAction:OnEnd")
end

return TryToCastSkillAction