---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/6 17:22
--- ui工具类
local Tools = {}

function Tools.GetGrayMaterial()
    return resMgr:LoadMaterialAtPath("Materials/UI/gray2D.mat")
end

return Tools