---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2020-05-05 14:59
--- 登录模块
local Login = class("Login", LuaObj)

function Login:Ctor()
    --print("Login:Ctor")
    Login.super.Ctor(self, "Prefabs/Login/Login.prefab", nil, Game.UICanvas.transform)
    self.LoginBtn = self.transform:Find("Button").gameObject
    self.OutLineBtn = self.transform:Find("ButtonOutline").gameObject
    self.TestButton = self.transform:Find("TestButton").gameObject

    self.camData = CameraExtensions.GetUniversalAdditionalCameraData(GetComponent.Canvas(Game.UICanvas).worldCamera)
    self.camData.renderType = CameraRenderType.Base


    local p = self.LoginBtn:GetComponent("PointerHandler") ---@type Prayer.PointerHandler

    NM.AddListenerPush(NM.PushNewChatMsg, function (data)
        print("Login:Ctor 收到推送", JSON.encode(data))
    end)

    --networkMgr:Connect()
    --AddEventListener(Stage, Event.FIXED_UPDATE, function ()
    --    print("Login:Ctor111", Input.mousePosition.x, Input.mousePosition.y)
    --end)

    AddButtonHandler(self.OutLineBtn, PointerHandler.CLICK, function ()

        --SM.AddScene("City", require("Modules.CityScene.CityScene"), function (scene)
        --    --require("Modules.FightScene.FightScene").New(scene)
        --    self:Destroy()
        --
        --end, true)

        SM.AddScene("War", require("Modules.WarScene.WarScene"), function (scene)
            --require("Modules.FightScene.FightScene").New(scene)
            self:Destroy()

            self.camData.renderType = CameraRenderType.Overlay
        end, true)
    end)

    AddButtonHandler(self.TestButton, PointerHandler.CLICK, function ()

        SM.AddScene("Test", nil, function (scene)

        end, true)
    end)

    self.nameText = GetComponent.Text(self.transform:Find("InputField/Text").gameObject)
    p:AddCall(PointerHandler.CLICK, function ()
        if self.nameText.text == "" then
            return
        end
        print("Login:Ctor 请求发送")
        NM.Send(NM.login, function (data)
            print("Login:Ctor 请求返回", JSON.encode(data))
            SM.AddScene("City", function (scene)
                local s = scene ---@type UnityEngine.SceneManagement.Scene
                print("Login:Ctor 你妹啊~~", s.name)
                require("Modules.CityScene.Model.CityData").myName = self.nameText.text
                require("Modules.CityScene.CityScene").New(scene)
                self:Destroy()

            end, true)
        end, self.nameText.text)

    end)

end


return Login
