---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2019-07-19 15:29
--- 用来绑定GameObject的回调
---@class LuaObj:LuaObj
---@field New fun(prefabPath:string, gameObject:UnityEngine.GameObject, parent:UnityEngine.Transform):LuaObj
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field component Prayer.OnDestroyHandler
local LuaObj = class("LuaObj")

---
function LuaObj:Ctor(prefabPath, gameObject, parent, log)
    --print("LuaObj:Ctor", prefabPath)
    self.log = log
    self.prefabPath = prefabPath
    if prefabPath then
        self:BindGameObject(CreatePrefab(prefabPath, parent))
    elseif gameObject and not tolua.isnull(gameObject) then
        self:BindGameObject(gameObject, parent)
    end
end


function LuaObj:BindGameObject(gameObject, parent)
    self.gameObject = gameObject ---@type UnityEngine.GameObject
    self.transform = gameObject.transform ---@type UnityEngine.Transform
    if parent then
        local pos = self.transform.localPosition
        local scale = self.transform.localScale
        local angel = self.transform.localEulerAngles
        self.transform:SetParent(parent)
        self.transform.localPosition = pos
        self.transform.localScale = scale
        self.transform.localEulerAngles = angel
    end

    ---检查是否需要注册 OnDestroy
    self.behaviorHandlers = {}
    local needOnDestroy = false
    for i, behaviorFunName in pairs(Event) do
        if self[behaviorFunName] then
            needOnDestroy = true
            if self.log then
                print("你妹啊~", behaviorFunName)
            end
            if behaviorFunName ~= Event.ON_DESTROY then
                table.insert(self.behaviorHandlers, {funName=behaviorFunName,
                                         handler=AddEventListener(Stage,behaviorFunName,handler(self, self[behaviorFunName]))})
            end
        end
    end
    if needOnDestroy == false then
        return
    end
    self.component = AddOrGetComponent(self.gameObject, Prayer.OnDestroyHandler) ---@type Prayer.OnDestroyHandler
    self.component.checkCall = function()
        self:RemoveBehaviorHandlers()
        if self.OnDestroy then
            self:OnDestroy()
        end
    end
end

---清理 BehaviorHandlers
function LuaObj:RemoveBehaviorHandlers()
    for i = 1, #self.behaviorHandlers do
        RemoveEventListener(Stage, self.behaviorHandlers[i].funName, self.behaviorHandlers[i].handler)
    end
end

function LuaObj:Show()
    self.gameObject:SetActive(true)
end

function LuaObj:Hide()
    self.gameObject:SetActive(false)
end


function LuaObj:Recycle()
    if self.prefabPath then
        RecyclePrefab(self.gameObject, self.prefabPath)
    end
    self.destroyed = true
    self:RemoveBehaviorHandlers()
end

function LuaObj:Destroy()
    --GameObject.Destroy(self.component)
    GameObject.Destroy(self.gameObject)
    self.destroyed = true
end

return LuaObj