---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2019-07-19 15:29
--- 用来绑定GameObject的回调
---@class LuaObj:LuaObj
---@field New fun(prefabPath:string, gameObject:UnityEngine.GameObject, parent:UnityEngine.Transform):LuaObj
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field component Prayer.LuaObj
local LuaObj = class("LuaObj")

---
function LuaObj:Ctor(prefabPath, gameObject, parent)
    --print("LuaObj:Ctor", prefabPath)
    self.prefabPath = prefabPath
    if prefabPath then
        self:BindGameObject(CreatePrefab(prefabPath, parent))
    elseif gameObject and not tolua.isnull(gameObject) then
        self:BindGameObject(gameObject, parent)
    end
end


function LuaObj:BindGameObject(gameObject, parent)
    self.gameObject = gameObject ---@type UnityEngine.GameObject
    self.transform = gameObject.transform ---@type UnityEngine.Transform
    if parent then
        local pos = self.transform.localPosition
        local scale = self.transform.localScale
        local angel = self.transform.localEulerAngles
        self.transform:SetParent(parent)
        self.transform.localPosition = pos
        self.transform.localScale = scale
        self.transform.localEulerAngles = angel
    end
    self.component = AddOrGetComponent(self.gameObject, Prayer.LuaObj) ---@type Prayer.LuaObj
    self.component.checkCall = function(funName)
        if self[funName] then
            self[funName](self)
        end
    end
end

function LuaObj:Show()
    self.gameObject:SetActive(true)
end

function LuaObj:Hide()
    self.gameObject:SetActive(false)
end


function LuaObj:Recycle()
    if self.prefabPath then
        RecyclePrefab(self.gameObject, self.prefabPath)
    end
    self.destroyed = true
end

function LuaObj:Destroy()
    --GameObject.Destroy(self.component)
    GameObject.Destroy(self.gameObject)
    self.destroyed = true
end

function LuaObj:OnDestroy()

end

return LuaObj