---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by likai.
--- DateTime: 2020-05-05 15:58
---
---@class LuaScene:LuaScene
local LuaScene = class("LuaScene")

---@param scene UnityEngine.SceneManagement.Scene
function LuaScene:Ctor(scene)
    self.scene = scene
    self.mainCamera = GetComponent.Camera(GameObject.FindWithTag("MainCamera"))
end

---@return UnityEngine.GameObject
function LuaScene:GetRootObjByName(name)
    local t = self.scene:GetRootGameObjects()
    for i = 0, t.Length-1 do
        --print("LuaScene:GetRootObjByName", i, t[i].name)
        if name == t[i].name then
            return t[i]
        end
    end
end

function LuaScene:Destroy()
    self.scene = nil
    self.mainCamera = nil
end

function LuaScene:RemoveScene()
    SM.RemoveScene(self.scene)
end

return LuaScene