---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sunshuo.
--- DateTime: 2023/2/3 10:34
--- panel基类
local LuaObj = require("Prayer.Core.LuaObj")
---@class UI.BasePanel:LuaObj
---@field New fun():LuaObj
---@field cfg panelConfig 页面配置
---@field prefabPath string prefab文件路径
---@field layer UnityEngine.Transform 所在涂层
local BasePanel = class("UI.BasePanel", LuaObj)
function BasePanel:Ctor()
end

---页面初始化
---@param cfg panelConfig 页面配置
---@vararg any 构造参数
function BasePanel:Init(cfg, ...)
    self.cfg = cfg
    self.prefabPath = cfg.prefabPath
    self.layer = UIMgr.GetLayer(cfg.layer or UILayerName.panel)
    self:BindGameObject(CreatePrefab(self.prefabPath, self.layer))
    self:OnInit(...)
end

---在初始化后
function BasePanel:OnInit()
    ---自动添加关闭界面点击事件
    local BtnClose = self.transform:Find("BtnClose")
    if BtnClose ~= nil then
        self.BtnClose = BtnClose.gameObject
        AddButtonHandler(self.BtnClose, PointerHandler.CLICK, self.Close, self)
    end
end

---移除事件监听
function BasePanel:RemoveListeners()
    RemoveButtonHandler(self.BtnClose, PointerHandler.CLICK, self.Close, self)
end

---关闭页面
function BasePanel:Close()
    UIMgr.ClosePanel(self.cfg)
end

---页面销毁时
function BasePanel:OnDestroy()
    BasePanel.super.OnDestroy(self)
    self:RemoveListeners()
    UIMgr.CheckPanelClean(self.cfg)
end

return BasePanel